spring:
  application:
    name: zuul-server
server:
  port: 9090
zuul-server: 
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
management:
  security:
    enabled: false
security:
  basic:
    enabled: false